name: easy_layout
description: A set of widgets that make it easy to create a layout with specified spacing between child widgets.
version: 0.1.0
author: Andy Chentsov
homepage:
repository: 
issues:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intersperse: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
