name: easy_layout
description: A set of widgets that make it easy to create a layout system with a specified spacing between child widgets. Spacings can be inherited by nested widgets.
version: 3.0.0
author: Andy Chentsov
homepage: https://github.com/andyduke/easy_layout/tree/master/package
repository: https://github.com/andyduke/easy_layout
issues: https://github.com/andyduke/easy_layout/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluid_kit:
    git:
      url: https://github.com/fabiocody/fluid_box
      ref: flutter-3.13
      path: package/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
